### ISSUE TITLE
Redundant Location Input Required When Editing Events

### ISSUE THREAD

**Issue by doucoureb** [BCStudentSoftwareDevTeam/celts#1338]
When editing an existing event on the website, users are prompted to re-enter the location, even though the location was previously specified when the event was initially created.
![Screenshot 2024-09-09 145630](https://github.com/user-attachments/assets/84fabb73-401f-46e4-86e6-499a026ae970)

**Comment by doucoureb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redundant Location Input Required When Editing Events](https://trello.com/c/yqFmN9Tr/823-redundant-location-input-required-when-editing-events)

**Comment by azabeli** [comment]
I was trying to get it resolved, but I can't find the issue at my end. When editing an event, everything looks fine, including the location. Based on the screenshot attached, I wonder if the error occurred because the event's  "Term" and the "Start Date" don't align as in the event term in 2021 while the start date is 2024.

**Comment by doucoureb** [comment]
I believe that was a previous issue, and I omitted to update my branch.
Issue solved!
