### ISSUE TITLE
Reset Program Eligibility Each Term

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#195]
The CELTS team informed us that the program-specific trainings only last the semester, so we need functionality to make the training for a program not count if the term of that training event does not match the current term.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #195: Reset Program Eligibility Each Term](https://trello.com/c/DEeSj2F9/351-celts-195-reset-program-eligibility-each-term)

**Comment by hmanalai** [comment]
This issue may have to be put on hold until PR #169 is merged because in that PR we keep track of individuals who have completed training. I am thinking we could add a conditional to [this function](https://github.com/BCStudentSoftwareDevTeam/celts/blob/8866a5ff82e8a4f0799441ce9713009b7c389ce0/app/logic/participants.py#L11) `trainedParticipants` that also checks whether the term for training is in the past.
