### ISSUE TITLE
Add Program Settings with Option to Edit Email Address and Sender Name

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#267]
We need a program settings section in our sidebar where admins can go in and change various settings related to CELTS programs.  Right now, the one we know they will need is the ability to edit the email address for the program and the sender name that the volunteers will get emails about the program from.

**Comment by Boorclark** [comment]
Notes for future development/thought process: 

 - In program.py there is not a column for program email addresses and sender names. This may mean that we need to add the sections to the DB in order to edit them. This may be different if these are hard coded. I think this website may help as far as concepts for this in the future: https://rockset.com/blog/change-data-capture-what-it-is-and-how-to-use-it/
 - Unless I am reading this wrong this does not seem like a good first issue as it will require an entire interface unless we wanted to add this to the setting page. I think it would make more sense to have its own interface though because it relates directly to the celts information. 
 - It may also make more sense to have this be a subsection of the actual event page. For example on the Adoption 101 page, it would make more sense that this even could be edited within its even information maybe as a subset of "Events List".
 - Will this have to interact directly with an email system? I don't know exactly how these systems work and if they are automated.

**Comment by mohamudm1** [comment]
Notes: 
I think this problem is not a good first issue and the reason I say that is because it will need to create a whole new interface.

**Comment by bledsoef** [comment]
Pull request merged.
