### ISSUE TITLE
Student Staff: the way we show the programs they are managing should be clearer

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#376]
Change how the programs that a student staff is managing are displayed.  A colon also needs to be added at the end of "User is a manager for the following programs"

**Comment by bledsoef** [comment]
I improved the look of this but here are a couple of other potential fixes:
- making the list of programs an accordion so that when you click on it the events for the program display.
- for admins, make the list of programs divided into two columns and make it a table that will make it look much better.

**Comment by bledsoef** [comment]
PR merged, closing issue.
