### ISSUE TITLE
Add the concept of a `Canceled Event` 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#985]
Canceled events would preserve their data and be visible to the same admins and staff. Need to evaluate existing queries for inclusion or exclusion of canceled events. Need to evaluate different views of an event and how Canceled is indicated. An automated email should be sent to people who have RSVPd to a canceled event.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add the concept of a Canceled Event #985](https://trello.com/c/HDQcYPit/651-add-the-concept-of-a-canceled-event-985)

**Comment by Mercy-Eze** [comment]
Following the daily stand-ups, changes have been made to the issue. Instead of hiding canceled events from student view, we now intend to flag as canceled to ensure students are aware. Additionally, we need to create an alert for CELTS admins to differentiate between canceled and deleted events in the modals. This requires updating the test cases and redefining the functions that utilize the userState parameter. Lastly, the automated email notification that was to be sent to people who have RSVPd to canceled events does not need to be implemented since we want the CELTS admins to be able to write and create their own email template.
